### ISSUE TITLE
 PayPal gateway has rejected request. Invalid token 

### ISSUE THREAD

**Issue by JithinTerrificminds** [hyva-themes/magento2-react-checkout-paypal-express#10]
The payapal express checkout is not generating any "TOKEN" and thus the getting the following issue :  PayPal gateway has rejected request. Invalid token 

**Adding the payment log:**

[2024-06-29T05:55:22.023926+00:00] main.DEBUG: array (
  'url' => 'https://api-3t.sandbox.paypal.com/nvp',
  'DoExpressCheckoutPayment' => 
  array (
    'TOKEN' => NULL,
    'PAYERID' => NULL,
    'PAYMENTACTION' => 'Authorization',
    'AMT' => '82.00',
    'CURRENCYCODE' => 'USD',
    'BUTTONSOURCE' => 'Magento_2_Community',
    'NOTIFYURL' => 'https://local.m246.test/paypal/ipn/',
    'RETURNFMFDETAILS' => 1,
    'SHIPPINGAMT' => '5.00',
    'ITEMAMT' => '77.00',
    'TAXAMT' => '0.00',
    'L_NUMBER0' => NULL,
    'L_NAME0' => 'Olivia 1/4 Zip Light Jacket',
    'L_QTY0' => 1,
    'L_AMT0' => '77.00',
    'BUSINESS' => 'tommy',
    'EMAIL' => 'jithin@test.com',
    'FIRSTNAME' => 'Jithin',
    'LASTNAME' => 'Jayan',
    'MIDDLENAME' => NULL,
    'SALUTATION' => NULL,
    'SUFFIX' => NULL,
    'COUNTRYCODE' => 'US',
    'STATE' => 'AZ',
    'CITY' => 'Scottsdale',
    'STREET' => '15205 North Kierland Blvd. Suite 100',
    'ZIP' => '85254',
    'PHONENUM' => '+64270129504',
    'SHIPTOCOUNTRYCODE' => 'US',
    'SHIPTOSTATE' => 'AZ',
    'SHIPTOCITY' => 'Scottsdale',
    'SHIPTOSTREET' => '15205 North Kierland Blvd. Suite 100',
    'SHIPTOZIP' => '85254',
    'SHIPTOPHONENUM' => '+64270129504',
    'SHIPTOSTREET2' => '',
    'STREET2' => '',
    'SHIPTONAME' => 'Jithin Jayan',
    'ADDROVERRIDE' => 1,
    'METHOD' => 'DoExpressCheckoutPayment',
    'VERSION' => '72.0',
    'USER' => '****',
    'PWD' => '****',
    'SIGNATURE' => '****',
  ),
  'response' => 
  array (
    'TIMESTAMP' => '2024-06-29T05:55:21Z',
    'CORRELATIONID' => 'eb1fa9066bcc7',
    'ACK' => 'Failure',
    'VERSION' => '72.0',
    'BUILD' => '58521741',
    'L_ERRORCODE0' => '10410',
    'L_SHORTMESSAGE0' => 'Invalid token',
    'L_LONGMESSAGE0' => 'Invalid token.',
    'L_SEVERITYCODE0' => 'Error',
  ),
) [] []

**Exception log :**

[2024-06-29T05:55:22.234020+00:00] main.ERROR: Unable to place order: A server error stopped your order from being placed. Please try to place your order again

GraphQL (3:3)
2: mutation placeOrderMutation($cartId: String!) {
3:   placeOrder(input: { cart_id: $cartId}){
     ^
4:     order {
 {"exception":"[object] (GraphQL\\Error\\Error(code: 0): Unable to place order: A server error stopped your order from being placed. Please try to place your order again at /var/www/html/vendor/webonyx/graphql-php/src/Error/Error.php:170)
[previous exception] [object] (Magento\\Framework\\GraphQl\\Exception\\GraphQlInputException(code: 0): Unable to place order: A server error stopped your order from being placed. Please try to place your order again at /var/www/html/vendor/magento/module-graph-ql/Helper/Error/AggregateExceptionMessageFormatter.php:62)
[previous exception] [object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): PayPal gateway has rejected request. Invalid token (#10410: Invalid token). at /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121)"} []
[2024-06-29T05:56:11.081727+00:00] main.ERROR: Syntax Error: Unexpected <EOF>

GraphQL (1:1)
1: 
   ^
 {"exception":"[object] (GraphQL\\Error\\SyntaxError(code: 0): Syntax Error: Unexpected <EOF> at /var/www/html/vendor/webonyx/graphql-php/src/Language/Parser.php:433)"} []

**system log:**

[2024-06-29T05:55:22.026156+00:00] main.CRITICAL: PayPal NVP gateway errors: Invalid token (#10410: Invalid token). Correlation ID: eb1fa9066bcc7. Version: 72.0. [] []

**debug log**

[2024-06-29T05:55:22.026156+00:00] main.CRITICAL: PayPal NVP gateway errors: Invalid token (#10410: Invalid token). Correlation ID: eb1fa9066bcc7. Version: 72.0. [] []
[2024-06-29T05:55:22.227861+00:00] main.DEBUG: cache_invalidate:  {"method":"POST","url":"https://local.m246.test/graphql","invalidateInfo":{"tags":["cat_p_1396","cat_p_1388"],"mode":"matchingAnyTag"}} []
[2024-06-29T05:55:22.234020+00:00] main.ERROR: Unable to place order: A server error stopped your order from being placed. Please try to place your order again

GraphQL (3:3)
2: mutation placeOrderMutation($cartId: String!) {
3:   placeOrder(input: { cart_id: $cartId}){
     ^
4:     order {
 {"exception":"[object] (GraphQL\\Error\\Error(code: 0): Unable to place order: A server error stopped your order from being placed. Please try to place your order again at /var/www/html/vendor/webonyx/graphql-php/src/Error/Error.php:170)
[previous exception] [object] (Magento\\Framework\\GraphQl\\Exception\\GraphQlInputException(code: 0): Unable to place order: A server error stopped your order from being placed. Please try to place your order again at /var/www/html/vendor/magento/module-graph-ql/Helper/Error/AggregateExceptionMessageFormatter.php:62)
[previous exception] [object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): PayPal gateway has rejected request. Invalid token (#10410: Invalid token). at /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121)"} []
[2024-06-29T05:56:11.081727+00:00] main.ERROR: Syntax Error: Unexpected <EOF>

GraphQL (1:1)
1: 
   ^
 {"exception":"[object] (GraphQL\\Error\\SyntaxError(code: 0): Syntax Error: Unexpected <EOF> at /var/www/html/vendor/webonyx/graphql-php/src/Language/Parser.php:433)"} []

**Comment by JithinTerrificminds** [comment]
Can someone please help me with this issue, the issue is happening in fresh magento insatance 2.4.6 . the payapal express checkout is working from pdp and min-cart.

**Comment by rajeev-k-tomy** [comment]
Did you make it work? then can you put the problem here so that it would be helpful for others @JithinTerrificminds ?

**Comment by rajeev-k-tomy** [comment]
I just tested this. It works just fine in my side.

**Comment by JithinTerrificminds** [comment]
@rajeev-k-tomy  The issue was related to module installation, the installation was done using https , after changing to ssh approach the issue got fixed.
