### ISSUE TITLE
PayPal NVP gateway errors: Invalid token (#10410: Invalid token). 

### ISSUE THREAD

**Issue by aterjung** [hyva-themes/magento2-react-checkout-paypal-express#4]
Hi,

i get this error in the log when i use Paypal in the Hyva Checkout. Using the Standard Checkout, the payment is successfull.

PayPal NVP gateway errors: Invalid token (#10410: Invalid token). 

I don`t know whats going on here. Anybody an idea?

**Comment by rajeev-k-tomy** [comment]
There are couple of things you can check here:

1. Check the store code passed is correct in all request.
2. Compare requests happening in luma checkout with the react checkout request. May be there are some differences?
